builders:
  schema_builder:
    import: "package:schema_builder/schema_builder.dart"
    builder_factories: ["build"]
    build_extensions: { ".dart": [".schema_builder.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
