
name: Flutter Package Release
on:
  push:
    tags:
      - 'v*' # Triggers the workflow when a tag starting with 'v' is pushed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Validate package
        run: |
          flutter analyze
          dart test
          flutter pub publish --dry-run
      
      - name: Publish to pub.dev
        run: flutter pub publish # Remove --dry-run to actually publish
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
